### ISSUE TITLE
flask run not working

### ISSUE THREAD

**Issue by asyncee** [bobthemighty/blog-code-samples#2]
Hello again, flask run is not working due to missing `config` module:
```
(env) ➜  04 git:(master) ✗ flask run
Traceback (most recent call last):
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 423, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 152, in __init__
    self._load_unlocked()
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/env/lib/python3.6/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/Users/asyncee/blog-code-samples/ports-and-adapters/04/issues/adapters/flask.py", line 3, in <module>
    from . import config
ImportError: cannot import name 'config'
```

**Comment by asyncee** [comment]
Working in 05.
